### ISSUE TITLE
draw audio waveform 

### ISSUE THREAD

**Issue by zyb8543d** [stefanrmmr/streamlit_audio_recorder#10]
Thank you very much. This tool is very useful. Will it support drawing audio waveforms？

**Comment by stefanrmmr** [comment]
@v-yunbin feel free to have a look at this project of mine - [beatinspect](https://github.com/stefanrmmr/beatinspect), which leverages the streamlit-audio-recorder component to build a dashboard for analyzing audio-data (including 2D and 3D audio waveform display)
