### ISSUE TITLE
Use recorded audio as a python object

### ISSUE THREAD

**Issue by pinnnnnnz** [stefanrmmr/streamlit_audio_recorder#7]
Are we able to support something like this? I am trying to record and video and send it immediately into a voice detection model

**Comment by Gabin-traverse** [comment]
me too, whisper allow only file in what i see. So im just waiting a responce from Stef

**Comment by Gabin-traverse** [comment]
got this https://gradio.app/real_time_speech_recognition/

**Comment by stefanrmmr** [comment]
@Gabin-traverse @pinnnnnnz In case it is sufficient to record audio using the component and wait until it has been transferred from the browser frontend to your backend python code, you can build your project just like @loukra did. Have a look at his fork of the original repo --> https://github.com/loukra/streamlit_audio_recorder. There you can see how to feed the wav_bytes audio data (as returned by the use of the audio recorder component) directly into an ML classification model once it arrives in the backend.   ![image](https://user-images.githubusercontent.com/82606558/213934222-42bca82a-7c1d-4344-a2a1-ba460575ce4e.png)

FYI, currently, the component does not support streaming audio data from the browser media-API into any kind of simultaneously running audio classification model in real-time.
