### ISSUE TITLE
Trouble with app

### ISSUE THREAD

**Issue by kolbydayley** [stefanrmmr/streamlit_audio_recorder#8]
![Screenshot 2023-02-27 at 10 21 37 AM](https://user-images.githubusercontent.com/17624536/221635400-48debd10-bf86-4d0d-8c4e-32e3a68f8725.png)

I am having some trouble using your app. When I deployed it in my own app, the "Start Recording" button didn't start a recording, it just recorded a 1ms long clip and then ends it.

**Comment by stefanrmmr** [comment]
the deployment of the demo app has been updated, thanks for your contribution!

**Comment by stefanrmmr** [comment]
the deployment of the demo app has been updated and should be working again, thanks for your contribution!
